### ISSUE TITLE
Willow-Grove background issue

### ISSUE THREAD

**Issue by fbm224** [smurphos/cinnamox_themes#2]
Hi,
I like the willow and kashmir themes a lot! thank you.

I found that using the Willow-Grove with the active corners - show all applications, it shows a green gradient instead of the desktop wallpaper like the Kashmir.

**Comment by smurphos** [comment]
Hi,

The default for both themes is a solid gradient unless you have amended the theme with the transparency script. I'm guessing that Willow-Grove is on the default No transparency still?

**Comment by fbm224** [comment]
After raising the issue i found the transparency settings, and as you suppose, it was solid. However I did not closed it, because I'm assuming I had a previous version of Kashmir installed, where it was also non-transparent, but the wallpaper was visible while using the active corners - show all applications, which in my personal opinion is the way it should be. At least I do not enjoy the solid gradient over the wallpaper. But I'm willing to concede it as a personal preference matter. 

On another theme (pun intented) have you considered making a sand color variation? something along the "#b8a427" hue 52

**Comment by smurphos** [comment]
Ok that makes sense. I added background gradient theming to the expo and scale view to all the themes on the last update. Prior to that they were the same as the default cinnamon theme.

If you want to revert to the previous without applying across the board transparency it is a pretty simple edit. Open the current `~/.themes/Cinnamox-Kashmir-Blue/cinnamon/cinnamon.css` file in a text editor (geany is good for this type of work) and navigate to line 516....

> .expo-background, .workspace-overview-background-shade {
> 	background-gradient-direction: radial;
> 	background-gradient-start: #577584;
> 	background-gradient-end: #28343a;
> }

Change it to

> .expo-background {
> 	background-gradient-direction: radial;
> 	background-gradient-start: #577584;
> 	background-gradient-end: #28343a;
> }
> .workspace-overview-background-shade {
> }
> 

I think you may be right that it looks better like this so will consider reverting to the previous behaviour or similar in the next update - this will be soon - probably no later than this weekend.

Re more color variations I'm not sure that I will upload any more than the eight to Cinnamon spices but I am working on some scripts and tools to allow end users to create their own versions from scratch. Having said that I'll mess around with that color code as a base and see how it looks.

Thanks for the feedback - always appreciated. Glad you like the themes overall.

**Comment by smurphos** [comment]
`.workspace-overview-background-shade` has a permanent transparency level as of [yesterdays release](https://github.com/smurphos/cinnamox_themes/releases/tag/v2018.03.02)

**Comment by fbm224** [comment]
Thank you !!
