### ISSUE TITLE
cinnamox_kashmir_blue, cinnamox_20180827, unreadable text (similar color for text and background) in firefox web form

### ISSUE THREAD

**Issue by jontis** [smurphos/cinnamox_themes#20]
![screenshot from 2018-10-14 13-10-02](https://user-images.githubusercontent.com/1307210/46915901-e5b87700-cfb2-11e8-9628-845c60ce86f3.png)

**Comment by jontis** [comment]
Apart from this tiny issue, great theme. Thank you for creating this :-)

**Comment by jontis** [comment]
I was not aware of that workaround until you mentioned it. It had not occurred to me that there would be a readme for themes. The workaround solved the problem. Please excuse my ignorance and thank you again.

**Comment by smurphos** [comment]
No worries, as long as the fix works all is good. Worth keeping a note of it if you ever experiment with other dark themes. Glad you are enjoying Kashmir Blue ;-)
